### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by anilmaurya** [apprentus/atom-ember-cli-helper#20]
1. Installed atom-ember-cli-helper
2. click on c/t button

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.4
**Thrown From**: [ember-cli-helper](https://github.com/apprentus/atom-ember-cli-helper) package, v0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/anil/.atom/packages/ember-cli-helper/lib/ember-cli-helper-view.coffee:84

TypeError: Cannot read property 'indexOf' of undefined
  at EmberCliHelperView.module.exports.EmberCliHelperView.getPathComponents (/Users/anil/.atom/packages/ember-cli-helper/lib/ember-cli-helper-view.coffee:84:26)
  at EmberCliHelperView.module.exports.EmberCliHelperView.switchFile (/Users/anil/.atom/packages/ember-cli-helper/lib/ember-cli-helper-view.coffee:96:51)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -8:12.7.0 settings-view:open (ul.list-inline.status-container)
  2x -8:04.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -8:03.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.11
auto-indent, v0.5.0
ember-cli-helper, v0.9.0
git-plus, v5.4.7
remember-session, v0.5.1
save-session, v0.15.7
terminal-plus, v0.6.5

# Dev
No dev packages
```

**Comment by mariusandra** [comment]
The `c/t` button toggles between the component and the template. From your description it seems you had no file open when pressing it. If so, then I have fixed the exception in v0.9.5.
